rndapp/proj/models.py
from rndapp.data import CRUDMixin, db

class Project(CRUDMixin, db.Model):
    __tablename__ = 'project_list'

    user_id = db.Column(db.Integer, db.ForeignKey('users_user.id'))
    title = db.Column(db.String)
    description = db.Column(db.String)

    def __repr__(self):
        return '<Project: {:id} {} {}>'.format(self.id,self.title, self.description)

    def __str__(self):
        return self.title    

rndapp/users/models.py
from random import SystemRandom

from backports.pbkdf2 import pbkdf2_hmac, compare_digest
from flask.ext.login import UserMixin
from sqlalchemy.ext.hybrid import hybrid_property

from rndapp.data import CRUDMixin, db

class User(UserMixin, CRUDMixin, db.Model):
    __tablename__ = 'users_user'

    name = db.Column(db.String(50))
    email = db.Column(db.String(120), unique=True)
    _password = db.Column(db.LargeBinary(120))
    _salt = db.Column(db.String(120))
    projects = db.relationship('Project',backref='owner',lazy='dynamic')

    @hybrid_property
    def password(self):
        return self._password

    # In order to ensure that passwords are always stored
    # hashed and salted in our database we use a descriptor
    # here which will automatically hash our password
    # when we provide it (i. e. user.password = "12345")
    @password.setter
    def password(self, value):
        # When a user is first created, give them a salt
        if self._salt is None:
            self._salt = bytes(SystemRandom().getrandbits(128))
        self._password = self._hash_password(value)

    def is_valid_password(self, password):
        """Ensure that the provided password is valid.

        We are using this instead of a ``sqlalchemy.types.TypeDecorator``
        (which would let us write ``User.password == password`` and have the incoming
        ``password`` be automatically hashed in a SQLAlchemy query)
        because ``compare_digest`` properly compares **all***
        the characters of the hash even when they do not match in order to
        avoid timing oracle side-channel attacks."""
        new_hash = self._hash_password(password)
        return compare_digest(new_hash, self._password)

    def _hash_password(self, password):
        pwd = password.encode("utf-8")
        salt = bytes(self._salt)
        buff = pbkdf2_hmac("sha512", pwd, salt, iterations=100000)
        return bytes(buff)

    def __repr__(self):
        return "<User #{:d}>".format(self.id)

rndapp/proj/forms.py
from datetime import datetime as dt

from flask.ext.wtf import Form
from wtforms import fields
from wtforms.validators import Required
from wtforms.ext.sqlalchemy.fields import QuerySelectField

class ProjectForm(Form):
	title = fields.StringField(validators=[Required()])
	description = fields.StringField(validators=[Required()])

rndapp/users/forms.py
from flask.ext.wtf import Form
from sqlalchemy.orm.exc import MultipleResultsFound, NoResultFound
from wtforms import fields
from wtforms.validators import Email, InputRequired, ValidationError

from .models import User


class LoginForm(Form):
    email = fields.StringField(validators=[InputRequired(), Email()])
    password = fields.PasswordField(validators=[InputRequired()])

    def validate_password(form, field):
        try:
            user = User.query.filter(User.email == form.email.data).one()
        except (MultipleResultsFound, NoResultFound):
            raise ValidationError("Invalid user")
        if user is None:
            raise ValidationError("Invalid user")
        if not user.is_valid_password(form.password.data):
            raise ValidationError("Invalid password")

        form.user = user


class RegistrationForm(Form):
    name = fields.StringField("Username")
    email = fields.StringField(validators=[InputRequired(), Email()])
    password = fields.PasswordField(validators=[InputRequired()])

    def validate_email(form, field):
        user = User.query.filter(User.email == field.data).first()
        if user is not None:
            raise ValidationError("A user with that email already exists")

rndapp/__init__.py
from flask import Flask

from .auth import login_manager
from .data import db
from .proj.views import application
from .users.views import users

app = Flask(__name__)
app.config.from_object('config')

db.init_app(app)

login_manager.init_app(app)

app.register_blueprint(application)
app.register_blueprint(users)

rndapp/auth.py
from flask.ext.login import AnonymousUserMixin, LoginManager

from rndapp.users.models import User

login_manager = LoginManager()

class AnonymousUser(AnonymousUserMixin):
    id = None

login_manager.anonymous_user = AnonymousUser

login_manager.login_view = "users.login"

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

rndapp/proj/views.py
from flask import abort, Blueprint, flash, jsonify, Markup, redirect, render_template, request, url_for
from flask.ext.login import current_user, login_required

from .forms import ProjectForm
from .models import Project
from rndapp.data import query_to_list

import config

application = Blueprint("application", __name__)
application.config = config.ANALYTICS

#@application.route("/")
#@application.route("/home")
#def index():
#    return render_template("index.html")

@application.route("/")
@application.route("/home")
def index():
    return render_template("comingsoon.html", surpress_rcontent=True)

@application.route('/about')
def about():
    return render_template("about.html")

@application.route('/events')
def events():
    return render_template("events.html")

@application.route('/news')
def news():
    return render_template("news.html")

@application.errorhandler(404)
def page_not_found(e):
    msgs = ['Oops!', 'Doh!', 'Oh no!', 'Aw shucks.', 'Golly.', 'Damn']
    return render_template("404.html", 
        msg=choice(msgs)), 404

@application.route("/projects", methods=("GET", "POST"))
def view_projects():
    form = ProjectForm()

    if form.validate_on_submit():
        Project.create(owner=current_user, **form.data)
        flash("Added project")
        return redirect(url_for(".view_projects"))

    #query = Project.query.filter(Project.user_id == current_user.id)
    query = Project.query
    data = query_to_list(query)
    results = []

    try:
        results = [next(data)]
        for row in data:
            row = [_make_link(cell) if i == 0 else cell
                   for i, cell in enumerate(row)]
            results.append(row)
    except StopIteration:
        pass

    return render_template("proj/projects.html", form=form, projects=results)    

@application.route("/projects/<int:site_id>")
@login_required
def view_project(site_id=None):
    
    query = Project.query.filter(Project.id == site_id)
    data = query_to_list(query)
    return render_template("proj/project.html", visits=data)

_LINK = Markup('<a href="{url}">{name}</a>')

def _make_link(site_id):
    url = url_for(".view_project", site_id=site_id)
    return _LINK.format(url=url, name=site_id)

rndapp/users/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask.ext.login import login_required, login_user, logout_user

from .forms import LoginForm, RegistrationForm
from .models import User

users = Blueprint('users', __name__)


@users.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        login_user(form.user)
        # flash("Logged in successfully.")
        # There's a subtle security hole in this code, which we will be fixing in our next article.
        # Don't use this exact pattern in anything important.
        return redirect(request.args.get("next") or url_for("application.index"))
    return render_template('login.html', form=form)


@users.route('/register', methods=('GET', 'POST'))
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.create(**form.data)
        login_user(user)
        return redirect(url_for('application.index'))
    return render_template('register.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('application.index'))

rndapp/templates/about.html
{% extends "base.html" %}

{% block head %}
<meta name="description" content="R&amp;D helps undergraduates find and develop their extracurricular interests through personal projects.">
{% endblock %}

{% block content %}
<h1>About</h1>
<hr>
<p class="text">We are a student organization that helps undergraduates find and develop research positions for unique projects. Our mission is to build a collaborative environment for members to challenge each other to pursue their personal interests. Our club encourages students to form a research community where they can freely cultivate innovative ideas and bring them to completion with the help of their peers. The organization will provide opportunities for undergraduate students to explore further their special interests and apply their skills with our guidance. Students may submit their own project ideas or apply to join a project that they are interested in. </p>
<p class="text">Undergraduates from all schools and colleges at UC Berkeley are welcome to apply. Opportunities are available year-round and new ideas are always encouraged. </p>

<h1>Contact</h1>
<hr>
<p class="text">For general questions or comments, please email <a href="mailto:team@rnd.berkeley.edu.">team@rnd.berkeley.edu</a></p>
<p class="text">For questions regarding a specific project, please apply and contact the person in charge.</p>

{% endblock %}

rndapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% if title %}{{title}}{% else %}Research &amp; Development at Berkeley{% endif %}</title>

  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700,100' rel='stylesheet' type='text/css'>

  <!-- Bootstrap -->
  <link href="{{ url_for('static', filename='bootstrap.css') }}" rel="stylesheet" />
  <!--<link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" />-->

  <!-- ours -->
  <link href="{{ url_for('static', filename='common.css') }}" rel="stylesheet" />

  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script type="text/javascript" language="javascript" charset="utf-8" src="{{ url_for('static', filename='scripts/bootstrap.min.js') }}"></script>

  {% block head %}
  {% endblock %}

  <!-- analytics -->
  {% if config["ANALYTICS"] %}
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44386221-1', 'berkeley.edu');
  ga('send', 'pageview');

  </script>
  {% endif %}
</head>


<body>
  <!-- Static navbar -->
  <div class="navbar navbar-fixed-top" style="padding-bottom:5px;background-color:rgba(0,0,0,0.5)">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><b class="green">R&amp;D</b> <b style="color:white;">at Berkeley</b></a>
      <div class="nav-collapse collapse" style="padding-top:5px;">
        <ul class="nav navbar-nav pull-right">
          <!--<li {% if request.path == "/" or request.path == "/home" %}class="active" {% endif %}><a href="home">Home</a></li>
          -->
          <!---->
          <li {% if request.path == "/about" %}class="active"{% endif %}><a href="about">About</a></li>
          <!--<li {% if request.path == "/news" %}class="active"{% endif %}><a href="news">news</a></li>-->
          <li {% if request.path == "/projects" %}class="active"{% endif %}><a href="projects">Projects</a></li>
          <!--<li {% if request.path == "/events" %}class="active"{% endif %}><a href="events">events</a></li>-->
          <!--<li {% if request.path == "/register" %}class="active"{% endif %}>
            {% if current_user.is_anonymous() %}
            <a href="{{url_for('users.register')}}">register</a>
            {% else %}
            <a href="#">{{current_user.name}}</a>
            {% endif %}
          </li>-->
          <li {% if request.path == "/login" %}class="active"{% endif %}>
            {% if current_user.is_anonymous() %}
            <a href="{{url_for('users.login')}}">Login</a>
            {% else %}
            <a href="{{url_for('users.logout')}}">Logout</a>
            {% endif %}
          </li>


        </ul>
        <!---->
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div id="wrap">
    {% block outcontent %}{% endblock %} <!-- when we need more customized control over page layout -->
    {% if surpress_rcontent is not defined %}
    <div id="rcontent">
      <div id="centerblock">
        {% with msgs = get_flashed_messages() %}
        {% if msgs %}
        <ul>
          {% for msg in msgs %}
          <li>{{msg}}</li>
          {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %} <!-- when we dont need precise control and just need to put content in -->
      </div>
    </div>
    {% endif %}
  </div>

  

  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <p class="text-muted credit padtop">
            <small>Designed by Students at UC Berkeley &copy; 2014</small>
          </p>
        </div>
        <div class="col-sm-6">
          <a href="http://www.ocf.berkeley.edu/"><img src="{{ url_for('static', filename='images/ocfbadge_mini8dark.png') }}" style="float:right;"></a>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

rndapp/templates/comingsoon.html
{% extends "base.html" %}
{% block head %}
  <meta name="description" content="We are R&amp;D, a UC Berkeley student organization for connecting undergraduates with technical extracurricular interests.">
  
  <link href="{{ url_for('static', filename='home.css') }}" rel="stylesheet" />
  <!-- parallax -->
  <script type="text/javascript" src="{{ url_for('static', filename='scripts/jquery.parallax-1.1.3.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='scripts/jquery.localscroll-1.2.7-min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='scripts/jquery.scrollTo-1.4.2-min.js') }}"></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $('#nav').localScroll(800);
    
    //.parallax(xPosition, speedFactor, outerHeight) options:
    //xPosition - Horizontal position of the element
    //inertia - speed to move relative to vertical scroll. Example: 0.1 is one tenth the speed of scrolling, 2 is twice the speed of scrolling
    //outerHeight (true/false) - Whether or not jQuery should use it's outerHeight option to determine when a section is in the viewport
    $('#intro').parallax("50%", 0.02);
    $('#second').parallax("50%", 0.02);
    $('.bg').parallax("50%", 0.4);
    $('#third').parallax("50%", 0.02);

  })
  </script>
{% endblock %}


{% block outcontent %}

<div id="intro">
  <div class="story">
    <div class="center">
      <img src="{{ url_for('static', filename='images/logo dark.svg') }}">
      <p class="title">Design. Engineer. Build.</p>
      <p>Welcome to <b class="green">Research &amp; Development at Berkeley</b>! We are a student organization here to help undergraduates find opportunities to collaborate with other students on personal projects. Undergraduates from all schools and colleges at UC Berkeley are welcome to apply for opportunities all year round.</p>
    </div>
  </div>
</div>

<div id="second" style="background-image:url('{{ url_for('static', filename='images/greenbackground.svg') }}');">
    <div class="container">
        <div class="row">
          <div class="story" style="margin: 0; width:100%">
            <div class="col-sm-5 tabled">
              <div class="tablec"><img src="{{ url_for('static', filename='images/flat cloc.svg') }}" style="height: 300px; width: auto; float: right;"></div>
            </div>
            <div class="col-sm-7 tabled">
              <div class="tablec tleft" style="padding-right: 25px;">
                <p class="title">Coming soon!</p>
                <p>Come back later in the school year to find out more about who we are and what we do.</p>
              </div>
          </div>
        </div>
    </div>
  </div>
</div>

{% endblock %}

rndapp/templates/data_list.html
{% extends "layout.html" %}
{% import "helpers/tables.html" as tables %}
{% block title %}View {{ super() }}{% endblock %}
{% block content %}
{{ super() }}
<table>
	{{ tables.render(data) }}
</table>
{% endblock content %}

rndapp/templates/events.html
{% extends "base.html" %}

{% block head %}
<meta name="description" content="Come check out our workshops and other student-lead events!">
{% endblock %}

{% block content %}
<h1>Events</h1>
<hr>
<p class="text">Our aim is to build an environment where undergraduates can discuss and collaborate on research and development projects. To forge a community among students of varying fields and interests, we hold several social events throughout the year for members to meet and have fun!</p>

<!-- Someone make a google calendar for all this and put it here -->
<ul>
  <li><p class="text">Welcoming</p>
    <p class="text">At the beginning of each semester, we invite all members to get together and pitch ideas for new projects while enjoying great food.</p></li>
  <li><p class="text">Project Showcase</p>
    <p class="text">At the end of the year, we invite all members to get together and present what they have accomplished. </p></li>
</ul>

{% endblock %}

rndapp/templates/helpers/forms.html
{% macro render(form) %}
<dl>
{% for field in form if field.type not in ["HiddenField", "CSRFTokenField"] %}
<dt>{{ field.label }}</dt>
<dd>{{ field }}
{% if field.errors %}
<ul class="errors">
{% for error in field.errors %}
<li>{{error}}</li>
{% endfor %}
</ul>
{% endif %}</dd>
{% endfor %}
</dl>
{{ form.hidden_tag() }}
{% endmacro %}

rndapp/templates/helpers/tables.html
{% macro render(data, headers=true) %}
{% for row in data %}
    {% set is_header_row = headers and loop.index == 1 %}
    {{ render_header(row) if is_header_row }}
    {% if (not headers and loop.index == 1) or (headers and loop.index == 2) %}
    <tbody>
    {% endif %}
    {{ render_row(row) if not is_header_row }}
{% endfor %}
</tbody>
{% endmacro %}

{% macro render_row(row) %}
    <tr>
    {% for cell in row %}
        <td>{{ cell }}</td>
    {% endfor %}
    </tr>
{% endmacro %}

{% macro render_header(row) %}
<thead>
    <tr>
    {% for cell in row %}
        <th>{{ cell }}</th>
    {% endfor %}
    </tr>
</thead>
{% endmacro %}

rndapp/templates/index.html
{% extends "layout.html" %}

{% block title %}Welcome!{% endblock %}

{% block content %}
{% endblock content %}

rndapp/templates/layout.html
<!DOCTYPE html>
<html>
	<head>
		<title>R&D at Berkeley</title>
	</head>
	<body>
		<header>
			<h1>{{ self.title() }}</h1>
			<nav>
				<ul>
					<li><a href="/">Home</a></li>
					<li><a href="/projects">Projects</a></li>
					<li>
						{% if current_user.is_anonymous() %}
						<a href="{{url_for('users.register')}}">Register</a> / <a href="{{url_for('users.login')}}">Log In</a>
						{% else %}
						Logged in as {{current_user.name}} <a href="{{url_for('users.logout')}}">Logout</a>
						{% endif %}
					</li>
				</ul>
			</nav>
		</header>
		{% set messages = get_flashed_messages() %}
		{% if messages %}
			<section>
				{% for message in messages %}
				<p>{{ message }}</p>
				{% endfor %}
			</section>
		{% endif %}
		<section>
			{% block content %}{% endblock %}
		</section>
	</body>
</html>

rndapp/templates/login.html
{% extends "base.html" %}
{% import "helpers/forms.html" as forms %}
{% block title %}Log in!{% endblock %}
{% block content %}
{{super()}}
<form action="{{ url_for('users.login', next=request.args.get('next', '')) }}" method="POST">
{{ forms.render(form) }}
<p><input type="Submit" value="Sign In"></p>
</form>

<center><h4 style="padding-top:10px;">Don't have an account? Register <a href="register">here!</a></></center>
{% endblock content %}

rndapp/templates/news.html
{% extends "base.html" %}

{% block head %}
<meta name="description" content="Come join us and see what we're up to - whether its building, coding, or designing.">
{% endblock %}

{% block content %}
<h1>News</h1>
<hr>
<!--News Template:
-->
<ul>
  <li><p class="text">hackTECH</p>
    <p class="text">Come attend hackTECH with us!</p>
    <p class="text">January 24-26th. SoCal. Largest Hackathon on the West Coast. #westcoastbestcoast. Register <a href ='http://www.hacktech.io'>here</a>!</p></li>
</ul>
{% endblock %}

rndapp/templates/proj/project.html
{% extends "layout.html" %}
{% import "helpers/tables.html" as tables %}
{% block title %}Project:{{ site }}{% endblock %}
{% block content %}
{{ super() }}
<p>Projects</p>
<table>
{{ tables.render(visits) }}
</table>
{% endblock content %}

rndapp/templates/proj/projects.html
{% extends "base.html" %}
{% import "helpers/forms.html" as forms %}
{% import "helpers/tables.html" as tables %}

{% block head %}
<script src="{{ url_for('static', filename='scripts/proj.js') }}"></script>
{% endblock %}

{% block content %}
<h1>Projects</h1>
<hr>
<p class="text">Our goal is to help undergraduate students deepen their academic knowledge and use it in a more applicable and hands-on setting in their areas of special interest. Our organization highly encourages students to submit project concepts for their own personal interests and we will work to bring their ideas to life as a club. In addition, if any of the descriptions of the projects in progress interest you, feel free to apply below to join. </p>
<p class="text">Here is a list of projects currently available. If you would like to submit a project or join one, request to join the club <a href='https://callink.berkeley.edu/organization/researchanddevelopment'>here</a> and we will contact you as soon as possible.</p>

<div id="addproj" class="phide">
  <a class="nodecor"><h1>Add A Project</h1></a>
  <form action="{{url_for('application.view_projects')}}" method="POST">
  <fieldset>
  <div id="projform">
    <hr>
    {{ forms.render(form) }}
    <p><input type="Submit" value="Add Project"></p>
  </div>
  </fieldset>
  </form>
</div>

<hr>

<table>
{{ tables.render(projects) }}
</table>

  
{% for entry in projects %}
<h1>{{entry[2]}}</h1>
<p class="text">{{entry[3]}}</p>
<hr>
{% endfor %}

{% endblock %}

rndapp/templates/register.html
{% extends "base.html" %}
{% import "helpers/forms.html" as forms %}
{% block title %}Sign up!{% endblock %}
{% block content %}
{{super()}}
<form action="{{url_for('users.register')}}" method="POST">
{{ forms.render(form) }}
<p><input type="Submit" value="Sign up!"></p>
</form>
{% endblock content %}